### ISSUE TITLE
Dev Server - extra watch target

### ISSUE THREAD

**Issue by richardguenther** [tylercampbell/eleventy-postcss-tailwind-esbuild-alpine#1]
Hi Tyler,

I'm nooby as well and trying different eleveny-starter templates. I've found another solution for the tailwind.css-refresh-problem. Your passthrough-copy solution works good - another solution is an option for the eleventy dev server (https://www.11ty.dev/docs/dev-server/)
```
  eleventyConfig.setServerOptions({
    watch: ["_site/assets/*.{js,css}"],
  });
```
With this option the devServer refreshes the page after postcss or esbuild changed their watched files and wrote them into the _site-folder

thank your for your starter-template 
richard

**Comment by tylercampbell** [comment]
@richardguenther this is an excellent find! Thank you for sharing! 🎉
